### ISSUE TITLE
Output is appended rather than overwriten 

### ISSUE THREAD

**Issue by djsmithme** [fairfieldt/coffeescript-concat#31]
Using coffeescript-concat with phpstorm on a filewatcher the output is appended to rather than overwritten. Is this intended functionality? How can I overwrite?

I'm just using the following args : '-R $FileDir$ -o compiled.coffee'

**Comment by fairfieldt** [comment]
Hey, thanks for the report!

I'm not seeing this behavior in my tests.  The command I'm running is `coffeescript-concat -R test/ -o out.coffee`.
Which, as expected, concats all the coffeescript files in `test/`.  I tried editing one of the files and re-running, but the contents of out.coffee were what I expected, new and not appended.  I also tried adding a new file to the directory, with the same result.

It seems like there's some sort of interaction with the phpstorm filewatcher.  Can you try running the standalone commands to verify that it doesn't happen when run that way?

**Comment by djsmithme** [comment]
I think you are right, seems like a phpstorm quirk. If i run 'coffeescript-concat -R test/ -o out.coffee.' I get the outputted file 'out.coffee.' This works and I'm left with a coffee script file has a trailing period, so all good. If run the same command removing the trailing period it will compile to a standard coffee extension and again works fine. Try to do this through the filewatcher and it starts the whole appending process. Ty for your help, I can work from terminal for now, I'll raise it with Jetbrains.

**Comment by fairfieldt** [comment]
Sounds good - reopen this if you find out part of the solution needs to happen on the coffeescript-concat side.

Good luck!
