### ISSUE TITLE
Gulp integration

### ISSUE THREAD

**Issue by d9k** [fairfieldt/coffeescript-concat#35]
Does any coffeescript-concat integration with gulp exist?
Or maybe it's better just use [gulp-grunt](https://www.npmjs.com/package/gulp-grunt) + coffeescript-concat grunt plugin for integration with gulp?

**Comment by fairfieldt** [comment]
Hey d9k, I don't know of any gulp integration.

I think you're right, if gulp-grunt would work for you, that's the way to go.

**Comment by artem328** [comment]
Hey!

I have written gulp module. Here the link https://www.npmjs.com/package/gulp-coffeescript-concat/

**Comment by fairfieldt** [comment]
Cool!  I'll add it to the readme.

**Comment by nelson6e65** [comment]
There is any usage examples (working examples) or doc? Maybe tests?

I want to use this package + gulp. :smiley:
