### ISSUE TITLE
Q: Can I use a main file to include other scripts?

### ISSUE THREAD

**Issue by nelson6e65** [fairfieldt/coffeescript-concat#37]
I didn't find any doc, so I don't know how handles paths.

How to make it work?

I want to use something like this files:

`main.coffee`
```coffee
#= require <ClassA.coffee>
#= require <ClassB.coffee>
#= require <NamespaceX/main.coffee>
# ...
```

`NamespaceX/main.coffee`

```coffee
# 
#= require <ClassA.coffee>
#= require <ClassB.coffee>
# ...

```

In a tree like:

- `NamespaceX`
  - `ClassA.coffee`
  - `ClassB.coffee`
  - `main.coffee`
- `ClassA.coffee`
- `ClassB.coffee`
- `main.coffee`

Then run something like:
```sh
coffeescript-concat main.coffee
```

...and compiles together.

In `#= require <FILE>`... FILE should be full path or relative to file?

**Comment by nelson6e65** [comment]
`main.coffee`:
```coffee
#= require <ClassA.coffee>
#= require <ClassB.coffee>
#= require <NamespaceX/main.coffee>

x = new ClassA()
```


`$ coffeescript-concat main.coffee -o concat.coffee`:

```bash
Error: couldn't find needed file: ClassA
Error: couldn't find needed file: ClassB
```

`concat.coffee`:
```coffee


#= require <NamespaceX/main.coffee>

x = new ClassA()


```

**Comment by fairfieldt** [comment]
If I understand correctly, you want to be able to have multiple files with the same name, at different paths, and then require them based on the path?

This is not currently supported.  It would probably pretty easy to add, though.  If you:

Change the regex in `findFileDependencies` to find dependencies with a '/'
https://github.com/fairfieldt/coffeescript-concat/blob/master/coffeescript-concat.coffee#L80

Change `findFileDefByName` within `concatFiles` to properly handle names that are paths
https://github.com/fairfieldt/coffeescript-concat/blob/master/coffeescript-concat.coffee#L184

**Comment by nelson6e65** [comment]
Yes. Well... no at all. 

I want to include all files in a `main.coffee` per directory (namespace) instead of adding each `.coffee` file in the command line.

I tried by using `-R .`, in the inverse way (`#= require <main.coffe>`), but add duplicates scripts.

`coffeescript-concat -R . -o concat.coffee`

I don't want to hack. :sweat_smile:

I think a workaround is concatenate each directory and then concatenate resulting `.coffee` scripts later.

**Comment by fairfieldt** [comment]
Cool, hopefully that works for you.  A feature like the one we discussed could definitely make sense in the tool, but I'm gonna close this for now.
